[package]
name = "pacote"
version = "1.0.0"
authors = ["Marcos Soares<mavmaso@gmail.com>"]
edition = "2021"

[lib]
name = "pacote"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.27.0"
csv = "1.1"
